//1- Esqueça de propósito. Comente a linha desenhar() de dentro do clique. Adicione uma tarefa. O dado entrou no vetor? Como você prova isso? E a tela, o que mostra?
//O dado entrou com sucesso no vetor, porém a tela permanece estagnada e não mostra a nova tarefa porque a função desenhar() não foi invocada para ler o array atualizado e renderizá-lo visualmente no HTML. A prova de que a informação foi inserida no vetor pode ser obtida adicionando temporariamente um console.log(tarefas) logo após a inserção do dado ou inspecionando o array diretamente através do Console das Ferramentas do Desenvolvedor (F12) no navegador.

//2-Perca o que foi digitado. Coloque um <input> dentro de cada <li>. Digite algo em um deles e clique em Adicionar. O que aconteceu com o que você digitou? Explique a causa.
//O conteúdo digitado no input foi completamente perdido após o clique. Isso acontece porque a função desenhar() utiliza uma abordagem destrutiva de renderização, limpando o contêiner principal para recriar todos os elementos da lista do zero a partir do vetor do JavaScript. Como o texto digitado existia apenas no estado volátil da tela (DOM) e nunca foi salvo de volta no array, ele é destruído junto com as tags antigas durante a reconstrução da interface.

//3- Conte quantos lugares. Faça a tela mostrar também quantas tarefas estão feitas e um aviso quando a lista estiver vazia. Quantos trechos diferentes do código você precisou tocar?
//Para exibir a contagem de tarefas concluídas e o aviso de lista vazia, foram modificados essencialmente dois trechos de código. O primeiro trecho alterado foi o HTML, onde foram criadas as tags necessárias para exibir os novos dados. O segundo trecho foi dentro da própria função desenhar() no JavaScript, onde foi implementada uma lógica de contagem usando filtros no array, além de uma estrutura condicional para injetar a mensagem de alerta quando o tamanho do vetor for igual a zero.     

//4-Quebre a cola. Renomeie no HTML o id="lista" para id="listaTarefas" e não mexa no JavaScript. O navegador reclama? Onde e quando o erro aparece?
//Sim, o navegador reclama do erro. Ele aparece no Console do Desenvolvedor (F12) no exato momento em que a função desenhar() tenta ser executada, o que costuma acontecer logo no carregamento inicial da página ou assim que o usuário tenta adicionar a primeira tarefa. O navegador exibirá uma mensagem de erro de tipo, informando que é impossível ler ou definir propriedades de um elemento nulo, já que o seletor do JavaScript continuará buscando pelo ID antigo que não existe mais no HTML.